
export const SET_ACTIVE_PASSWORDS = 'SET_ACTIVE_PASSWORDS';
export const SET_INACTIVE_PASSWORDS = 'SET_INACTIVE_PASSWORDS';
export const SET_PASSWORD = 'SET_PASSWORD';
export const DELETE_PASSWORD = 'DELETE_PASSWORD';
export const CREATE_PASSWORD = 'CREATE_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const SET_GEN_PASSWORD = 'SET_GEN_PASSWORD';